ALTER TABLE facilities
  ADD COLUMN IF NOT EXISTS opening_time TIME NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS closing_time TIME NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS allows_overnight TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS allows_all_day TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_duration_hours INT NULL DEFAULT NULL;

